from __future__ import annotations
import re

LANG_EN = "EN"
LANG_UK = "UKR"

UI = {
    LANG_EN: {
        "images_controls": "Images Controls",
        "video_controls": "Video Controls",
        "choose_image": "📂 Choose image",
        "toggle_detection": "🪄 Toggle Detection",
        "clear_image": "🗑 Clear image",
        "choose_folder": "📁 Choose images folder",
        "batch": "⚙ Batch process folder",
        "save": "💾 Save results",
        "play": "▶ Play",
        "pause": "⏸ Pause",
        "choose_video": "🎥 Choose video",
        "seek_plus": "⏩ +10s",
        "seek_minus": "⏪ -10s",
        "speed2": "⏫ Speed x2",
        "speed1": "⏺ Speed 1x",
        "speed05": "🐢 Speed 0.5x",
        "detection_result": "Detection Result",
        "no_detections_yet": "No detections yet",
        "no_detections": "No detections",
        "detected_signs": "Detected sign(s): ",
        "objects": "Objects",
        "fps": "FPS",
        "inference": "Inference",
        "confidence": "Confidence",
        "log": "Log",
        "folder_loaded": "Folder loaded: {n} images",
        "batch_done": "Batch done: {n} images saved to: {path}",
        "preprocess_on": "🧪 Preprocess: ON",
        "preprocess_off": "🧪 Preprocess: OFF",
    },
    LANG_UK: {
        "images_controls": "Керування зображеннями",
        "video_controls": "Керування відео",
        "choose_image": "📂 Обрати зображення",
        "toggle_detection": "🪄 Показати/сховати детект",
        "clear_image": "🗑 Очистити екран",
        "choose_folder": "📁 Обрати папку зображень",
        "batch": "⚙ Пакетна обробка папки",
        "save": "💾 Зберегти результати",
        "play": "▶ Пуск",
        "pause": "⏸ Пауза",
        "choose_video": "🎥 Обрати відео",
        "seek_plus": "⏩ +10с",
        "seek_minus": "⏪ -10с",
        "speed2": "⏫ Швидкість x2",
        "speed1": "⏺ Швидкість 1x",
        "speed05": "🐢 Швидкість 0.5x",
        "detection_result": "Результат розпізнавання",
        "no_detections_yet": "Поки що нічого не знайдено",
        "no_detections": "Нічого не знайдено",
        "detected_signs": "Знайдено: ",
        "objects": "Об’єкти",
        "fps": "FPS",
        "inference": "Інференс",
        "confidence": "Впевненість",
        "log": "Лог",
        "folder_loaded": "Папку завантажено: {n} зображень",
        "batch_done": "Готово: {n} зображень збережено в: {path}",
        "preprocess_on": "🧪 Предобробка: ON",
        "preprocess_off": "🧪 Предобробка: OFF",
    },
}

EMOJI = {
    "bicycle": "🚲",
    "bus_stop": "🚌",
    "children": "🚸",
    "crosswalk": "🚶",
    "do_not_enter": "⛔",
    "do_not_turn_left": "⬅️🚫",
    "do_not_turn_right": "➡️🚫",
    "do_not_u_turn": "↩️🚫",
    "give_way": "⚠️",
    "left_lane_enter": "↙️",
    "left_right_lane": "↔️",
    "left_sharp_curve": "↩️",
    "left_turn": "⬅️",
    "light_green": "🟢",
    "light_red": "🔴",
    "light_traffic": "🚦",
    "light_yellow": "🟡",
    "no_overtaking": "🚫🚗",
    "no_overtaking_truck": "🚫🚚",
    "no_parking": "🅿️🚫",
    "no_passing": "🚫↔️",
    "no_stop": "🛑🚫",
    "no_waiting": "⏳🚫",
    "parking": "🅿️",
    "railway_crossing": "🚆",
    "refueling": "⛽",
    "right_sharp_curve": "↪️",
    "right_turn": "➡️",
    "Priority road": "⭐",
    "road_rough": "🪨",
    "road_slippery": "🧊",
    "road_work": "🚧",
    "rough_road": "🛣️",
    "round_about": "🔄",
    "snow_warning": "❄️",
    "stop": "🛑",
    "t_intersection_l": "┤",
    "truck": "🚚",
    "u_turn": "↩️",
    "warning": "⚠️",
    "axle_load_limit": "⚖️",
    "barrier_ahead": "🚧",
    "cattle": "🐄",
    "compulsory_ahead": "⬆️",
    "compulsory_ahead_or_left": "⬆️⬅️",
    "compulsory_ahead_or_right": "⬆️➡️",
    "compulsory_cycle_track": "🚲",
    "compulsory_keep_left": "⬅️",
    "compulsory_keep_right": "➡️",
    "compulsory_min_speed": "⬆️💨",
    "compulsory_sound_horn": "📢",
    "cross_road": "➕",
    "cycle_crossing": "🚲🚶",
    "cycle_prohibited": "🚲🚫",
    "dangerous_dip": "〰️",
    "direction": "🧭",
    "falling_rocks": "🪨⬇️",
    "ferry": "⛴️",
    "gap_in_median": "↕️",
    "height_limit": "↕️",
    "horn_prohibited": "📢🚫",
    "length_limit": "📏",
    "load_limit": "⚖️",
    "narrow_bridge": "🌉",
    "narrow_road": "🛣️",
    "pass_either_side": "↔️",
    "width_limit": "↔️",
}

CLASS_EN = {
    "bicycle": "Bicycle",
    "bus_stop": "Bus Stop",
    "children": "Children Crossing",
    "crosswalk": "Pedestrian Crossing",
    "do_not_enter": "Do Not Enter",
    "do_not_turn_left": "No Left Turn",
    "do_not_turn_right": "No Right Turn",
    "do_not_u_turn": "No U-Turn",
    "give_way": "Give Way",
    "left_lane_enter": "Merge Left Lane",
    "left_right_lane": "Left / Right Lane",
    "left_sharp_curve": "Sharp Left Curve",
    "left_turn": "Left Turn",
    "light_green": "Green Light",
    "light_red": "Red Light",
    "light_traffic": "Traffic Light",
    "light_yellow": "Yellow Light",
    "no_overtaking": "No Overtaking",
    "no_overtaking_truck": "No Overtaking (Trucks)",
    "no_parking": "No Parking",
    "no_passing": "No Passing",
    "no_stop": "No Stopping",
    "no_waiting": "No Waiting",
    "parking": "Parking",
    "railway_crossing": "Railway Crossing",
    "refueling": "Fuel Station",
    "right_sharp_curve": "Sharp Right Curve",
    "right_turn": "Right Turn",
    "Priority road": "Priority Road",
    "road_rough": "Rough Road",
    "road_slippery": "Slippery Road",
    "road_work": "Road Works",
    "rough_road": "Uneven Road",
    "round_about": "Roundabout",
    "snow_warning": "Snow Warning",
    "stop": "Stop",
    "t_intersection_l": "T-Intersection (Left)",
    "truck": "Truck",
    "u_turn": "U-Turn",
    "warning": "General Warning",
    "axle_load_limit": "Axle Load Limit",
    "barrier_ahead": "Barrier Ahead",
    "cattle": "Cattle Crossing",
    "compulsory_ahead": "Go Straight",
    "compulsory_ahead_or_left": "Go Straight or Left",
    "compulsory_ahead_or_right": "Go Straight or Right",
    "compulsory_cycle_track": "Cycle Track",
    "compulsory_keep_left": "Keep Left",
    "compulsory_keep_right": "Keep Right",
    "compulsory_min_speed": "Minimum Speed",
    "compulsory_sound_horn": "Use Horn",
    "cross_road": "Cross Road",
    "cycle_crossing": "Cycle Crossing",
    "cycle_prohibited": "No Cycles",
    "dangerous_dip": "Dangerous Dip",
    "direction": "Direction",
    "falling_rocks": "Falling Rocks",
    "ferry": "Ferry",
    "gap_in_median": "Median Gap",
    "height_limit": "Height Limit",
    "horn_prohibited": "No Horn",
    "length_limit": "Length Limit",
    "load_limit": "Load Limit",
    "narrow_bridge": "Narrow Bridge",
    "narrow_road": "Narrow Road",
    "pass_either_side": "Pass Either Side",
    "width_limit": "Width Limit",
}

CLASS_UK = {
    "bicycle": "Велосипеди",
    "bus_stop": "Автобусна зупинка",
    "children": "Діти",
    "crosswalk": "Пішохідний перехід",
    "do_not_enter": "В’їзд заборонено",
    "do_not_turn_left": "Поворот ліворуч заборонено",
    "do_not_turn_right": "Поворот праворуч заборонено",
    "do_not_u_turn": "Розворот заборонено",
    "give_way": "Дати дорогу",
    "left_lane_enter": "Злиття в ліву смугу",
    "left_right_lane": "Смуги ліворуч/праворуч",
    "left_sharp_curve": "Крутий поворот ліворуч",
    "left_turn": "Поворот ліворуч",
    "light_green": "Зелений сигнал",
    "light_red": "Червоний сигнал",
    "light_traffic": "Світлофор",
    "light_yellow": "Жовтий сигнал",
    "no_overtaking": "Обгін заборонено",
    "no_overtaking_truck": "Обгін вантажівкам заборонено",
    "no_parking": "Паркування заборонено",
    "no_passing": "Випередження заборонено",
    "no_stop": "Зупинку заборонено",
    "no_waiting": "Стоянку заборонено",
    "parking": "Паркування",
    "railway_crossing": "Залізничний переїзд",
    "refueling": "АЗС",
    "right_sharp_curve": "Крутий поворот праворуч",
    "right_turn": "Поворот праворуч",
    "Priority road": "Головна дорога",
    "road_rough": "Нерівна дорога",
    "road_slippery": "Слизька дорога",
    "road_work": "Дорожні роботи",
    "rough_road": "Погана дорога",
    "round_about": "Кільцевий рух",
    "snow_warning": "Сніг",
    "stop": "Стоп",
    "t_intersection_l": "Т-перехрестя (ліворуч)",
    "truck": "Вантажівки",
    "u_turn": "Розворот",
    "warning": "Попередження",
    "axle_load_limit": "Обмеження навантаження на вісь",
    "barrier_ahead": "Перешкода попереду",
    "cattle": "Худоба",
    "compulsory_ahead": "Тільки прямо",
    "compulsory_ahead_or_left": "Прямо або ліворуч",
    "compulsory_ahead_or_right": "Прямо або праворуч",
    "compulsory_cycle_track": "Велодоріжка",
    "compulsory_keep_left": "Триматися лівіше",
    "compulsory_keep_right": "Триматися правіше",
    "compulsory_min_speed": "Мінімальна швидкість",
    "compulsory_sound_horn": "Подати звуковий сигнал",
    "cross_road": "Перехрестя",
    "cycle_crossing": "Переїзд велосипедистів",
    "cycle_prohibited": "Велосипеди заборонено",
    "dangerous_dip": "Небезпечна вибоїна",
    "direction": "Напрямок",
    "falling_rocks": "Падіння каміння",
    "ferry": "Пором",
    "gap_in_median": "Розрив розділювальної",
    "height_limit": "Обмеження висоти",
    "horn_prohibited": "Сигнал заборонено",
    "length_limit": "Обмеження довжини",
    "load_limit": "Обмеження маси",
    "narrow_bridge": "Вузький міст",
    "narrow_road": "Вузька дорога",
    "pass_either_side": "Об’їзд з будь-якого боку",
    "width_limit": "Обмеження ширини",
}

_SPEED_RE = re.compile(r"^speed_limit_(\d+)$")

def emoji_for(raw: str) -> str:
    if _SPEED_RE.match(raw):
        return "🚫💨"
    return EMOJI.get(raw, "🔷")


def human_class_name(raw: str, lang: str) -> str:
    m = _SPEED_RE.match(raw)
    if m:
        n = m.group(1)
        if lang == LANG_UK:
            return f"Обмеження швидкості {n}"
        return f"Speed Limit {n}"

    if lang == LANG_UK:
        return CLASS_UK.get(raw, raw)
    return CLASS_EN.get(raw, raw)

def pretty_class(raw: str, lang: str) -> str:
    return f"{emoji_for(raw)} {human_class_name(raw, lang)}"
